# Generated by Django 5.1.3 on 2025-01-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
